### ISSUE TITLE
Not showing my custom shipping method

### ISSUE THREAD

**Issue by umarch06** [karliuka/m2.TrackingLink#2]
I added a custom shipping method to M2, but this extension is not showing tracking url there.

**Comment by karliuka** [comment]
Apparently, your custom shipping method does not support shipping tracking.
Please, check that in the carrier model of your module there is a **isTrackingAvailable** method and it returns the **true**.

**Comment by umarch06** [comment]
yes, it worked. Thanks, I will close issue now.

**Comment by karliuka** [comment]
please, this is important
 In the Magento Admin Panel after sending a tracking info email, open shipment view page and click tracking number link. 

![tracking](https://user-images.githubusercontent.com/1991955/35755455-00787c76-0870-11e8-8583-91e6c47c98e4.png)


If you see error of popup window add to your carrier model method **getTracking**

    protected $_trackFactory;
    protected $_trackStatusFactory;

    public function __construct(
        \Magento\Shipping\Model\Tracking\ResultFactory $trackFactory,
        \Magento\Shipping\Model\Tracking\Result\StatusFactory $trackStatusFactory,
		...
    ) {
        $this->_trackFactory = $trackFactory;
        $this->_trackStatusFactory = $trackStatusFactory;
		...
    }

    /**
     * Get tracking
     *
     * @param string|string[] $trackings
     * @return Result
     */
	public function getTracking($trackings)
	{
		$result = $this->_trackFactory->create();
		
		$tracking = $this->_trackStatusFactory->create();
		$tracking->setCarrier($this->_code);
		$tracking->setCarrierTitle($this->getConfigData('title'));
		$tracking->setTracking($trackings);
		
		$result->append($tracking);
		
		return $result;
	}

**Comment by umarch06** [comment]
@karliuka, a question related to your extension. Right now I have written an observer for event `sales_order_shipment_save_before` where I call an api when a shipping is saved and I add track to current shipment (I think this doesn't sound sensible to write observer for each shipping method to register shipping in courier website).

I think there would must be a method for each shipment method that when we click on submit shipment it would call method of selected shipping method and book shipping to courier website and get track number from it and add it to shipment automatically? Probably you may understand it better from [this](https://magento.stackexchange.com/questions/211543/magento-2-override-shipping-module-to-call-api-from-backend) link.

**Comment by umarch06** [comment]
@karliuka did you have time to look into this problem?

**Comment by karliuka** [comment]
In most cases, the seller physically delivers orders to the courier in the office or the courier takes orders from the client's office. Only after transferring the order from the seller to the courier you get the tracking number. Next, you can create a shipping and add a this tracking number to it.
If your courier has an api of creating a shipping remotely and receiving a tracking number, then yes, the implementation of the automatic tracking number addition will be successful.

**Comment by umarch06** [comment]
I have the api available to register shipment, but problems is that I want to register it with Carrier class itself but not observer like other shipment modules(dhl, fedx) do. Is there any method i need to override so in that I can call api?

**Comment by karliuka** [comment]
Sorry, I don't know the answer to your question right now)
