### ISSUE TITLE
The UPS and the USPS tracking urls need swapped

### ISSUE THREAD

**Issue by holdenmonroe** [karliuka/m2.TrackingLink#3]
UPS = United Parcel Service: https://wwwapps.ups.com/WebTracking/track?track=yes&trackNums={{number}}

USPS = United States Postal Service: https://tools.usps.com/go/TrackConfirmAction_input?qtc_tLabels1={{number}}

Other than that great extension! Thanks!

**Comment by karliuka** [comment]
Thank you.
You're right. I confused links)
