### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by intelsteel** [karliuka/m2.TrackingLink#4]
i used it ... but its not working

**Comment by karliuka** [comment]
it seems that you did something wrong

**Comment by intelsteel** [comment]
hi,
i just installed it. but its not working.

Regards,
    I Love My INDIA   
 

    On Tuesday, 7 August 2018, 12:15:11 GMT+5:30, Karliuka Vitalii <notifications@github.com> wrote:  
 
 
it seems that you did something wrong
